language: node_js
services:
  - redis-server
  - mongodb
node_js:
  0.10
notifications:
  email: false
before_script: make jshint
script:
  - make test-coverage
  - make test-int
after_success:
  - make coveralls
